// Mocks generated by Mockito 5.4.6 from annotations
// in logsheet_app/test/features/daily_storage_analytical_report_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:logsheet_app/data/remote/quality/daily_storage_tank_analytical/daily_storage_tank_analytical_from_db_entity.dart'
    as _i3;
import 'package:logsheet_app/data/remote/quality/daily_storage_tank_analytical/daily_storage_tank_analytical_to_db_entity.dart'
    as _i2;
import 'package:logsheet_app/data/repositories/quality/daily_storage_tank_analytical/daily_storage_tank_analytical_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDailyStorageTankAnalyticalToDbEntity_0 extends _i1.SmartFake
    implements _i2.DailyStorageTankAnalyticalToDbEntity {
  _FakeDailyStorageTankAnalyticalToDbEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeDailyStorageTankAnalyticalFromDbEntity_1 extends _i1.SmartFake
    implements _i3.DailyStorageTankAnalyticalFromDbEntity {
  _FakeDailyStorageTankAnalyticalFromDbEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [DailyStorageTankAnalyticalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyStorageTankAnalyticalRepository extends _i1.Mock
    implements _i4.DailyStorageTankAnalyticalRepository {
  MockDailyStorageTankAnalyticalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> insertDailyStorageTankAnalytical({
    required _i2.DailyStorageTankAnalyticalToDbEntity? report,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertDailyStorageTankAnalytical, [], {
              #report: report,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateAutoNumber(String? plantCode, int? newAutoNumber) =>
      (super.noSuchMethod(
            Invocation.method(#updateAutoNumber, [plantCode, newAutoNumber]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getLatestId(String? plantCode) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestId, [plantCode]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<List<_i3.DailyStorageTankAnalyticalFromDbEntity>>
  getAllDailyStorageTankReport(String? date, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDailyStorageTankReport, [date, role]),
            returnValue: _i5.Future<
              List<_i3.DailyStorageTankAnalyticalFromDbEntity>
            >.value(<_i3.DailyStorageTankAnalyticalFromDbEntity>[]),
          )
          as _i5.Future<List<_i3.DailyStorageTankAnalyticalFromDbEntity>>);

  @override
  _i5.Future<bool> deleteDailyStorageTankAnalyticalReport(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDailyStorageTankAnalyticalReport, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updatedeleteDailyStorageTankAnalyticalReport(
    _i2.DailyStorageTankAnalyticalToDbEntity? entity,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatedeleteDailyStorageTankAnalyticalReport, [
              entity,
              id,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateApproveRejectToHeader({
    required String? id,
    required String? approvedBy,
    required String? status,
    required String? role,
    String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateApproveRejectToHeader, [], {
              #id: id,
              #approvedBy: approvedBy,
              #status: status,
              #role: role,
              #remarks: remarks,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i3.DailyStorageTankAnalyticalFromDbEntity>>
  getAllDailyStorageTankApproval() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDailyStorageTankApproval, []),
            returnValue: _i5.Future<
              List<_i3.DailyStorageTankAnalyticalFromDbEntity>
            >.value(<_i3.DailyStorageTankAnalyticalFromDbEntity>[]),
          )
          as _i5.Future<List<_i3.DailyStorageTankAnalyticalFromDbEntity>>);
}

/// A class which mocks [DailyStorageTankAnalyticalToDbEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyStorageTankAnalyticalToDbEntity extends _i1.Mock
    implements _i2.DailyStorageTankAnalyticalToDbEntity {
  MockDailyStorageTankAnalyticalToDbEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.DailyStorageTankAnalyticalToDbEntity copyWith({
    String? id,
    String? company,
    String? plant,
    DateTime? transactionDate,
    DateTime? postingDate,
    String? tankNo,
    String? oilType,
    int? kapasitasTanki,
    int? quantity,
    int? emptySpace,
    int? suhu,
    double? qpFFA,
    String? qpMoisture,
    int? qpColorR,
    int? qpColorY,
    double? qpIV,
    double? qpPV,
    String? qpSlipMeltingPoint,
    double? qpCloudPoint,
    double? qpANV,
    double? betaCarotene,
    double? qpP,
    double? qpDobi,
    double? qpTotox,
    String? qpOdor,
    String? remarks,
    String? flag,
    String? entryBy,
    DateTime? entryDate,
    String? preparedBy,
    DateTime? preparedDate,
    String? preparedStatus,
    String? preparedStatusRemarks,
    String? approvedBy,
    DateTime? approvedDate,
    String? approvedStatus,
    String? approvedStatusRemarks,
    String? updatedBy,
    DateTime? updatedDate,
    String? formNo,
    DateTime? dateIssued,
    String? revisionNo,
    DateTime? revisionDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #company: company,
              #plant: plant,
              #transactionDate: transactionDate,
              #postingDate: postingDate,
              #tankNo: tankNo,
              #oilType: oilType,
              #kapasitasTanki: kapasitasTanki,
              #quantity: quantity,
              #emptySpace: emptySpace,
              #suhu: suhu,
              #qpFFA: qpFFA,
              #qpMoisture: qpMoisture,
              #qpColorR: qpColorR,
              #qpColorY: qpColorY,
              #qpIV: qpIV,
              #qpPV: qpPV,
              #qpSlipMeltingPoint: qpSlipMeltingPoint,
              #qpCloudPoint: qpCloudPoint,
              #qpANV: qpANV,
              #betaCarotene: betaCarotene,
              #qpP: qpP,
              #qpDobi: qpDobi,
              #qpTotox: qpTotox,
              #qpOdor: qpOdor,
              #remarks: remarks,
              #flag: flag,
              #entryBy: entryBy,
              #entryDate: entryDate,
              #preparedBy: preparedBy,
              #preparedDate: preparedDate,
              #preparedStatus: preparedStatus,
              #preparedStatusRemarks: preparedStatusRemarks,
              #approvedBy: approvedBy,
              #approvedDate: approvedDate,
              #approvedStatus: approvedStatus,
              #approvedStatusRemarks: approvedStatusRemarks,
              #updatedBy: updatedBy,
              #updatedDate: updatedDate,
              #formNo: formNo,
              #dateIssued: dateIssued,
              #revisionNo: revisionNo,
              #revisionDate: revisionDate,
            }),
            returnValue: _FakeDailyStorageTankAnalyticalToDbEntity_0(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #company: company,
                #plant: plant,
                #transactionDate: transactionDate,
                #postingDate: postingDate,
                #tankNo: tankNo,
                #oilType: oilType,
                #kapasitasTanki: kapasitasTanki,
                #quantity: quantity,
                #emptySpace: emptySpace,
                #suhu: suhu,
                #qpFFA: qpFFA,
                #qpMoisture: qpMoisture,
                #qpColorR: qpColorR,
                #qpColorY: qpColorY,
                #qpIV: qpIV,
                #qpPV: qpPV,
                #qpSlipMeltingPoint: qpSlipMeltingPoint,
                #qpCloudPoint: qpCloudPoint,
                #qpANV: qpANV,
                #betaCarotene: betaCarotene,
                #qpP: qpP,
                #qpDobi: qpDobi,
                #qpTotox: qpTotox,
                #qpOdor: qpOdor,
                #remarks: remarks,
                #flag: flag,
                #entryBy: entryBy,
                #entryDate: entryDate,
                #preparedBy: preparedBy,
                #preparedDate: preparedDate,
                #preparedStatus: preparedStatus,
                #preparedStatusRemarks: preparedStatusRemarks,
                #approvedBy: approvedBy,
                #approvedDate: approvedDate,
                #approvedStatus: approvedStatus,
                #approvedStatusRemarks: approvedStatusRemarks,
                #updatedBy: updatedBy,
                #updatedDate: updatedDate,
                #formNo: formNo,
                #dateIssued: dateIssued,
                #revisionNo: revisionNo,
                #revisionDate: revisionDate,
              }),
            ),
          )
          as _i2.DailyStorageTankAnalyticalToDbEntity);
}

/// A class which mocks [DailyStorageTankAnalyticalFromDbEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyStorageTankAnalyticalFromDbEntity extends _i1.Mock
    implements _i3.DailyStorageTankAnalyticalFromDbEntity {
  MockDailyStorageTankAnalyticalFromDbEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.DailyStorageTankAnalyticalFromDbEntity copyWith({
    String? id,
    String? company,
    String? plant,
    String? transactionDate,
    String? postingDate,
    String? tankNo,
    String? oilType,
    String? kapasitasTanki,
    String? quantity,
    String? emptySpace,
    String? suhu,
    String? qpFFA,
    String? qpMoisture,
    String? qpColorR,
    String? qpColorY,
    String? qpIV,
    String? qpPV,
    String? qpSlipMeltingPoint,
    String? qpCloudPoint,
    String? qpANV,
    String? betaCarotene,
    String? qpP,
    String? qpDobi,
    String? qpTotox,
    String? qpOdor,
    String? remarks,
    String? flag,
    String? entryBy,
    String? entryDate,
    String? preparedBy,
    String? preparedDate,
    String? preparedStatus,
    String? preparedStatusRemarks,
    String? approvedBy,
    String? approvedDate,
    String? approvedStatus,
    String? approvedStatusRemarks,
    String? updatedBy,
    String? updatedDate,
    String? formNo,
    String? dateIssued,
    String? revisionNo,
    String? revisionDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #company: company,
              #plant: plant,
              #transactionDate: transactionDate,
              #postingDate: postingDate,
              #tankNo: tankNo,
              #oilType: oilType,
              #kapasitasTanki: kapasitasTanki,
              #quantity: quantity,
              #emptySpace: emptySpace,
              #suhu: suhu,
              #qpFFA: qpFFA,
              #qpMoisture: qpMoisture,
              #qpColorR: qpColorR,
              #qpColorY: qpColorY,
              #qpIV: qpIV,
              #qpPV: qpPV,
              #qpSlipMeltingPoint: qpSlipMeltingPoint,
              #qpCloudPoint: qpCloudPoint,
              #qpANV: qpANV,
              #betaCarotene: betaCarotene,
              #qpP: qpP,
              #qpDobi: qpDobi,
              #qpTotox: qpTotox,
              #qpOdor: qpOdor,
              #remarks: remarks,
              #flag: flag,
              #entryBy: entryBy,
              #entryDate: entryDate,
              #preparedBy: preparedBy,
              #preparedDate: preparedDate,
              #preparedStatus: preparedStatus,
              #preparedStatusRemarks: preparedStatusRemarks,
              #approvedBy: approvedBy,
              #approvedDate: approvedDate,
              #approvedStatus: approvedStatus,
              #approvedStatusRemarks: approvedStatusRemarks,
              #updatedBy: updatedBy,
              #updatedDate: updatedDate,
              #formNo: formNo,
              #dateIssued: dateIssued,
              #revisionNo: revisionNo,
              #revisionDate: revisionDate,
            }),
            returnValue: _FakeDailyStorageTankAnalyticalFromDbEntity_1(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #company: company,
                #plant: plant,
                #transactionDate: transactionDate,
                #postingDate: postingDate,
                #tankNo: tankNo,
                #oilType: oilType,
                #kapasitasTanki: kapasitasTanki,
                #quantity: quantity,
                #emptySpace: emptySpace,
                #suhu: suhu,
                #qpFFA: qpFFA,
                #qpMoisture: qpMoisture,
                #qpColorR: qpColorR,
                #qpColorY: qpColorY,
                #qpIV: qpIV,
                #qpPV: qpPV,
                #qpSlipMeltingPoint: qpSlipMeltingPoint,
                #qpCloudPoint: qpCloudPoint,
                #qpANV: qpANV,
                #betaCarotene: betaCarotene,
                #qpP: qpP,
                #qpDobi: qpDobi,
                #qpTotox: qpTotox,
                #qpOdor: qpOdor,
                #remarks: remarks,
                #flag: flag,
                #entryBy: entryBy,
                #entryDate: entryDate,
                #preparedBy: preparedBy,
                #preparedDate: preparedDate,
                #preparedStatus: preparedStatus,
                #preparedStatusRemarks: preparedStatusRemarks,
                #approvedBy: approvedBy,
                #approvedDate: approvedDate,
                #approvedStatus: approvedStatus,
                #approvedStatusRemarks: approvedStatusRemarks,
                #updatedBy: updatedBy,
                #updatedDate: updatedDate,
                #formNo: formNo,
                #dateIssued: dateIssued,
                #revisionNo: revisionNo,
                #revisionDate: revisionDate,
              }),
            ),
          )
          as _i3.DailyStorageTankAnalyticalFromDbEntity);
}
